import { AuctionItem } from './types';

// Real auction photography sourced locally from /public/auction-pics
const PIC = (file: string) => `/auction-pics/${file}`;

export const MOCK_ITEMS: AuctionItem[] = [
  {
    id: '1',
    title: '2011 BMW Z4 sDrive35is',
    category: 'Sports & Collector',
    year: 2011,
    make: 'BMW',
    model: 'Z4 sDrive35is',
    location: 'Toronto, ON',
    currentBid: 28500,
    endTime: '2026-05-09T18:00:00Z',
    timeLeft: '3d 2h',
    auctionSource: 'Unreserved.net',
    imageUrl: PIC('2011_bmw_z4-sdrive35is_77_ext_2011-z4-auction-engine-31658.webp'),
    status: 'live',
    views: 2980,
    fairValueRange: [32000, 38000],
    recommendedMaxBid: 36000,
    buyerEdgeScore: 'Strong Buy',
    confidenceScore: 92,
    isNative: true,
    sourceSlug: 'unreserved',
    sourceByline: 'Zero-fee marketplace for unreserved auctions',
    sourceDescription: 'Unreserved.net is a next-generation auction platform with zero buyer fees, transparent pricing, and real-time market intelligence on every listing.',
    currency: 'CAD',
    editorialBadge: 'Cinematic Feature',
    whyWatch: 'Final-year sDrive35is with the N54 twin-turbo. Bidding ~20% below fair value with three days to run.',
    confidence: 5,
    editorialSections: ['editor_picks', 'best_under_market', 'native_listings', 'cinematic_features'],
    listingType: 'cinematic_feature',
    cinematicTagline: 'The last hand-built Z4 with the legendary N54 — captured on film.',
    cinematicPosterUrl: PIC('2011_bmw_z4-sdrive35is_77_ext_2011-z4-auction-engine-31658.webp'),
    whyWatching: 'This 2011 Z4 sDrive35is made the front page because it is a native unreserved listing with a verified walkaround, full service file, clean Ontario title, and a cinematic feature treatment. The current bid is tracking well below the comparable cohort and the collector market for E89 Z4s is firming up.',
    whatToKnow: [
      'Native unreserved listing — fully reviewed pre-launch',
      'N54 twin-turbo, 7-speed DCT, sport package',
      'Cinematic feature: full walkaround film + service file on record',
      'Current bid $28,500 CAD vs. fair-value band $32–38K',
      'Three days remaining; bid history is steady, no late spike yet'
    ],
    knownIssues: 'Standard E89 maintenance items to verify — water pump, charge pipes, oil filter housing. No leaks or codes flagged at the pre-listing inspection.',
    cautionFlags: ['Verify Terms'],
    sellerNotes: 'Single-owner since 2014. Garage-kept year-round, summer-driven only. Recent service: oil + filter (1,200 km ago), full coolant flush, new charge pipes. Original window sticker, both keys, complete service binder. Selling because I bought a new car for my daughter and need the garage space.',
    comparableSales: [
      { title: '2011 BMW Z4 sDrive35is — 51K km', date: '2026-04-18', location: 'Vancouver, BC', price: 36500, source: 'Bring a Trailer' },
      { title: '2010 BMW Z4 sDrive35i — 64K km', date: '2026-03-22', location: 'Calgary, AB', price: 32100, source: 'Cars & Bids' },
      { title: '2012 BMW Z4 sDrive28i — 38K km', date: '2026-03-04', location: 'Toronto, ON', price: 29800, source: 'Unreserved.net' },
      { title: '2011 BMW Z4 sDrive35is — 72K km', date: '2026-02-11', location: 'Ottawa, ON', price: 34200, source: 'Bring a Trailer' }
    ],
    publicQA: [
      { question: 'Has the DCT had its fluid serviced?', askedBy: 'turbo_collector', askedAt: '2 days ago', answer: 'Yes — DCT fluid + filter done at 78,000 km (current odo 84,200). Receipt in the listing photo set.', answeredBy: 'Seller', answeredAt: '2 days ago' },
      { question: 'Any dealer service records before 2014?', askedBy: 'BMWfan_88', askedAt: '1 day ago', answer: 'Original purchase + first service at Pfaff BMW Toronto. Records uploaded to the doc bundle.', answeredBy: 'Seller', answeredAt: '1 day ago' },
      { question: 'Will you ship to the US?', askedBy: 'detroit_buyer', askedAt: '6 hours ago' }
    ],
    auctionTerms: [
      'Bidding closes at the time displayed; auto-extends 2 minutes for any bid in the final 2 minutes.',
      'Buyer pays applicable provincial sales tax on the hammer price.',
      'No buyer fee. Zero commission to Unreserved.net buyers.',
      'Vehicle must be picked up or shipping arranged within 7 days of close.',
      'Inspection and verification at buyer expense; seller cooperates with reasonable requests.'
    ]
  },
  {
    id: '2',
    title: '2008 Land Rover LR3 HSE',
    category: 'SUVs',
    year: 2008,
    make: 'Land Rover',
    model: 'LR3 HSE',
    location: 'Edmonton, AB',
    price: 8400,
    saleDate: '2026-04-28',
    auctionSource: 'Ritchie Bros.',
    imageUrl: PIC('fde60690-64d3-47a9-b729-712fbd199340.jpeg'),
    status: 'sold',
    views: 1120,
    fairValueRange: [7500, 9500],
    recommendedMaxBid: 9200,
    buyerEdgeScore: 'Fair Market',
    confidenceScore: 82,
    isNative: false,
    sourceSlug: 'ritchie_bros',
    sourceByline: 'Global industrial auctioneer since 1958',
    sourceDescription: 'Hosts no-reserve auctions across North America, specializing in heavy equipment, trucks, and industrial machinery.',
    sourceUrl: 'https://www.rbauction.com/listing/example-2',
    currency: 'CAD',
    editorialBadge: 'High Trust',
    whyWatch: 'Cleared mid-band on a no-reserve LR3 with verified mileage. A textbook used-luxury sale.',
    confidence: 4,
    editorialSections: ['editor_picks'],
    listingType: 'curated_external',
    whyWatching: 'This LR3 made the front page because it sold within the fair-value band on a vehicle with documented service. The HSE 4.4L has held value well in Western Canada thanks to genuine all-weather capability and an active enthusiast community.',
    whatToKnow: [
      'Hammer at $8,400 CAD — middle of $7.5–9.5K band',
      '4.4L V8 HSE trim, third-row seating',
      'Edmonton — strong demand for AWD/4x4 in the prairies',
      'Confirmed sold via Ritchie Bros. results feed'
    ],
    knownIssues: 'Standard LR3 watch-points: air suspension condition, transmission fluid history, and timing chain tensioner. Buyer should confirm with seller post-sale.',
    cautionFlags: ['Verify Terms']
  },
  {
    id: '3',
    title: '2012 Ford F-150 Lariat EcoBoost',
    category: 'Trucks',
    year: 2012,
    make: 'Ford',
    model: 'F-150 Lariat',
    location: 'Calgary, AB',
    currentBid: 21800,
    endTime: '2026-05-08T20:00:00Z',
    timeLeft: '2d 4h',
    auctionSource: 'Unreserved.net',
    imageUrl: PIC('93dbc8db-7158-49a7-b341-47d88938dd1c.jpeg'),
    status: 'live',
    views: 1860,
    fairValueRange: [24000, 29000],
    recommendedMaxBid: 27500,
    buyerEdgeScore: 'Strong Buy',
    confidenceScore: 94,
    isNative: true,
    sourceSlug: 'unreserved',
    sourceByline: 'Zero-fee marketplace for unreserved auctions',
    sourceDescription: 'Unreserved.net is a next-generation auction platform with zero buyer fees, transparent pricing, and real-time market intelligence on every listing.',
    currency: 'CAD',
    editorialBadge: 'Cinematic Feature',
    whyWatch: 'Native Lariat with EcoBoost, full walkaround on file, and a clean Alberta title — bidding under market.',
    confidence: 5,
    editorialSections: ['native_listings', 'editor_picks', 'best_under_market', 'cinematic_features'],
    listingType: 'cinematic_feature',
    cinematicTagline: 'A clean Alberta-spec Lariat — captured around the working ranch.',
    cinematicPosterUrl: PIC('93dbc8db-7158-49a7-b341-47d88938dd1c.jpeg'),
    whyWatching: 'This 2012 Ford F-150 Lariat EcoBoost made the front page because it is a native unreserved listing with verified seller notes, a clean presentation, strong buyer demand, and a current bid below comparable market value. We also produced a cinematic walkaround film for this listing.',
    whatToKnow: [
      'Native Unreserved.net listing — fully reviewed pre-launch',
      '3.5L EcoBoost, Lariat trim, leather, sunroof',
      'Cinematic feature: walkaround film + service file on record',
      'Current bid $21,800 CAD vs. $24–29K fair-value band',
      'Verified seller, clean Alberta title, full service history'
    ],
    knownIssues: 'No material concerns flagged. EcoBoost cam phasers and intercooler condensation are standard cohort watch-points; both inspected and noted as healthy.',
    sellerNotes: 'Original owner since new. Trailered ~2,400 lb seasonally, no commercial use. Recent: spark plugs + ignition coils (Motorcraft, 6,000 km ago), brake pads + rotors (front, 4,000 km ago), oil + filter every 8,000 km on full synthetic. Selling to consolidate to a single half-ton.',
    comparableSales: [
      { title: '2012 Ford F-150 Lariat EcoBoost — 142K km', date: '2026-04-12', location: 'Edmonton, AB', price: 26800, source: 'Unreserved.net' },
      { title: '2013 Ford F-150 Lariat EcoBoost — 168K km', date: '2026-03-29', location: 'Saskatoon, SK', price: 24500, source: 'Manheim' },
      { title: '2012 Ford F-150 XLT EcoBoost — 158K km', date: '2026-03-08', location: 'Calgary, AB', price: 22300, source: 'Adesa' }
    ],
    publicQA: [
      { question: 'Any rust on the frame or rockers?', askedBy: 'prairie_buyer', askedAt: '3 days ago', answer: 'No structural rust. Surface flash on a couple of underbody bolts only — visible in photos #14–17.', answeredBy: 'Seller', answeredAt: '3 days ago' },
      { question: 'Cam phaser noise on cold start?', askedBy: 'ecoboost_owner', askedAt: '1 day ago', answer: 'No. Last service noted phasers are within tolerance.', answeredBy: 'Seller', answeredAt: '1 day ago' }
    ],
    auctionTerms: [
      'Bidding closes at the time displayed; auto-extends 2 minutes for any bid in the final 2 minutes.',
      'Buyer pays Alberta provincial taxes on the hammer price.',
      'No buyer fee. Zero commission to Unreserved.net buyers.',
      'Vehicle must be picked up or shipping arranged within 10 days of close.',
      'Inspection by buyer at seller\'s residence by appointment.'
    ]
  },
  {
    id: '4',
    title: '2014 Mazda CX-9 GT AWD',
    category: 'SUVs',
    year: 2014,
    make: 'Mazda',
    model: 'CX-9 GT',
    location: 'Saskatoon, SK',
    currentBid: 13900,
    endTime: '2026-05-07T15:30:00Z',
    timeLeft: '1d 0h',
    auctionSource: 'IronPlanet',
    imageUrl: PIC('129d38ff-ce22-45b1-acb6-12d844ccf88c.jpeg'),
    status: 'live',
    views: 920,
    fairValueRange: [16000, 19500],
    recommendedMaxBid: 18500,
    buyerEdgeScore: 'Strong Buy',
    confidenceScore: 86,
    isNative: false,
    sourceSlug: 'iron_planet',
    sourceLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/IronPlanet_logo.svg/200px-IronPlanet_logo.svg.png',
    sourceByline: 'Online marketplace for used heavy equipment',
    sourceDescription: 'IronPlanet is an online marketplace for buying and selling used vehicles and equipment with IronClad inspection.',
    sourceUrl: 'https://www.ironplanet.com/listing/example-4',
    currency: 'CAD',
    editorialBadge: 'Under Market',
    whyWatch: 'Closes in under a day, current bid $2K+ below comparable AWD CX-9 GTs in the prairies.',
    confidence: 4,
    editorialSections: ['editor_picks', 'best_under_market'],
    listingType: 'curated_external',
    cautionFlags: ['Verify Terms'],
    whyWatching: 'CX-9 GT trims with AWD, leather, and the Bose pack consistently clear $16K+ in this region. Final hours and the bid hasn\'t caught up. Worth watching closely if you need a 7-seater under $18K.',
    whatToKnow: [
      'Current bid $13,900 CAD vs. fair-value band $16–19.5K',
      'GT trim — leather, sunroof, Bose, AWD',
      'Saskatoon — quick transport for AB / SK / MB buyers',
      'Closes in ~24h, IronClad inspection on file'
    ],
    knownIssues: 'Inspect water pump and PCM grounds — known cohort items on the 3.7L. Both checked at the auction inspection and noted as serviceable.'
  },
  {
    id: '5',
    title: '2010 Polaris Ranger XP 800',
    category: 'Side-by-Sides',
    year: 2010,
    make: 'Polaris',
    model: 'Ranger XP 800',
    location: 'Lethbridge, AB',
    price: 7400,
    saleDate: '2026-04-22',
    auctionSource: 'BigIron',
    imageUrl: PIC('e371f0a9-c035-4d36-8123-94d1bcba5627.jpeg'),
    status: 'sold',
    views: 612,
    fairValueRange: [7000, 8800],
    recommendedMaxBid: 8200,
    buyerEdgeScore: 'Moderate Edge',
    confidenceScore: 88,
    isNative: false,
    sourceSlug: 'bigiron',
    sourceByline: 'Online unreserved auction for ag & construction',
    sourceDescription: 'BigIron Auctions specializes in farm equipment, side-by-sides, and transportation assets. All items sell unreserved with no minimum bids and no buyer fees.',
    sourceUrl: 'https://www.bigiron.com/listing/example-5',
    currency: 'CAD',
    editorialBadge: 'Hidden Gem',
    whyWatch: 'Working Ranger XP with cargo bed and brushguard — landed at the low end of the band.',
    confidence: 4,
    editorialSections: ['hidden_gems'],
    listingType: 'curated_external',
    whyWatching: 'A clean working Ranger that closed at the low end of the fair-value band. Strong demand from acreage owners and small-contractor cohort makes these move fast — 2010 vintage with the 800cc twin is the sweet spot.',
    whatToKnow: [
      'Hammer at $7,400 CAD — low end of $7–8.8K band',
      '800cc twin, dump bed, brush guard, winch',
      'Lethbridge, AB — strong rural Western Canada demand',
      'Confirmed sold via BigIron results feed'
    ],
    knownIssues: 'Camo wrap shows wear — cosmetic only. Drivetrain noted as healthy at inspection.'
  },
  {
    id: '6',
    title: '2014 RAM 1500 SLT Crew Cab 4x4',
    category: 'Trucks',
    year: 2014,
    make: 'RAM',
    model: '1500 SLT',
    location: 'Brandon, MB',
    currentBid: 17200,
    endTime: '2026-05-08T22:00:00Z',
    timeLeft: '2d 6h',
    auctionSource: 'PurpleWave',
    imageUrl: PIC('0bb30942-605a-4a2d-9b19-8fa92b2f3ffb.jpeg'),
    status: 'live',
    views: 1340,
    fairValueRange: [20000, 24500],
    recommendedMaxBid: 23000,
    buyerEdgeScore: 'Strong Buy',
    confidenceScore: 81,
    isNative: false,
    sourceSlug: 'purplewave',
    sourceByline: 'No-reserve online auctioneer',
    sourceDescription: 'PurpleWave runs unreserved online auctions for trucks, equipment, and ag assets across North America.',
    sourceUrl: 'https://www.purplewave.com/listing/example-6',
    currency: 'CAD',
    editorialBadge: 'Editor Pick',
    whyWatch: 'HEMI Crew Cab with mud terrains — bidding around 20% below comparable AB/SK sales.',
    confidence: 4,
    editorialSections: ['editor_picks', 'best_under_market'],
    listingType: 'curated_external',
    cautionFlags: ['Verify Terms'],
    whyWatching: 'Working-spec RAM 1500 SLT Crew Cab with the 5.7L HEMI. The current bid sits well below recent prairie comps for clean examples in this trim. Mud terrain tires and farm-yard provenance check out in the photos.',
    whatToKnow: [
      'Current bid $17,200 CAD vs. fair-value band $20–24.5K',
      '5.7L HEMI, Crew Cab, 4x4, SLT trim',
      'Brandon, MB — short transport to SK and ON',
      'No-reserve close in ~2 days'
    ],
    knownIssues: 'Surface dust and farm-yard wear visible. No paint or rust concerns flagged in the photo set; verify undercarriage in person if planning long-distance haul.'
  },
  {
    id: '7',
    title: '2011 Ford F-150 XLT FX4 SuperCrew',
    category: 'Trucks',
    year: 2011,
    make: 'Ford',
    model: 'F-150 XLT FX4',
    location: 'Red Deer, AB',
    currentBid: 14400,
    endTime: '2026-05-06T22:30:00Z',
    timeLeft: '0h 38m',
    auctionSource: 'Adesa',
    imageUrl: PIC('56aced56-89f1-4449-b1d7-ee75a717ae9c.jpeg'),
    status: 'live',
    views: 1810,
    fairValueRange: [17500, 21000],
    recommendedMaxBid: 20000,
    buyerEdgeScore: 'Strong Buy',
    confidenceScore: 84,
    isNative: false,
    sourceSlug: 'adesa',
    sourceByline: 'Wholesale auto and commercial auctions',
    sourceDescription: 'Adesa runs dealer-only and commercial auctions across North America.',
    sourceUrl: 'https://www.adesa.com/listing/example-7',
    currency: 'CAD',
    editorialBadge: 'Ending Soon',
    whyWatch: 'Closes within the hour — bid still tracking ~$3K under comparable EcoBoost FX4 trucks.',
    confidence: 4,
    editorialSections: ['editor_picks', 'best_under_market'],
    listingType: 'curated_external',
    cautionFlags: ['Verify Terms'],
    whyWatching: 'Final hour, and the bid hasn\'t caught up to the comparable cohort. FX4 SuperCrews in this band typically clear $17.5K+ in Alberta. Worth watching closely.',
    whatToKnow: [
      'Current bid $14,400 CAD vs. fair-value band $17.5–21K',
      '3.5L EcoBoost, XLT FX4 package, SuperCrew',
      'Red Deer, AB — central prairies',
      'Closes in ~38 minutes'
    ],
    knownIssues: 'Aftermarket black wheels — original wheels not included per the listing. Factor wheel-set replacement if originals matter to you.'
  },
  {
    id: '8',
    title: '2011 Jeep Liberty Sport 4x4',
    category: 'SUVs',
    year: 2011,
    make: 'Jeep',
    model: 'Liberty Sport',
    location: 'Saskatoon, SK',
    currentBid: 9100,
    endTime: '2026-05-10T16:00:00Z',
    timeLeft: '4d 0h',
    auctionSource: 'Unreserved.net',
    imageUrl: PIC('16e1ae6b-8e5a-42fe-b6ef-4394eef8cda1.jpeg'),
    status: 'live',
    views: 540,
    fairValueRange: [10500, 12500],
    recommendedMaxBid: 12000,
    buyerEdgeScore: 'Moderate Edge',
    confidenceScore: 90,
    isNative: true,
    sourceSlug: 'unreserved',
    sourceByline: 'Zero-fee marketplace for unreserved auctions',
    sourceDescription: 'Unreserved.net is a next-generation auction platform with zero buyer fees, transparent pricing, and real-time market intelligence on every listing.',
    currency: 'CAD',
    editorialBadge: 'Native Listing',
    whyWatch: 'Native Liberty with full service file and clean SK title — currently bidding below the comparable band.',
    confidence: 5,
    editorialSections: ['native_listings', 'editor_picks'],
    listingType: 'native',
    whyWatching: 'This 2011 Jeep Liberty made the front page because it is a native unreserved listing with verified seller notes, a documented service history, and a clean SK title. Bidding is currently below the comparable cohort with several days to run.',
    whatToKnow: [
      'Native Unreserved.net listing — fully reviewed pre-launch',
      'Current bid $9,100 CAD vs. $10.5–12.5K fair-value band',
      '3.7L V6, 4x4, clean SK title',
      '4 days remaining — full walkaround on file'
    ],
    knownIssues: 'No material concerns flagged. Common KK Liberty watch-points (sunroof drains, door wiring harness) inspected and noted as healthy.',
    sellerNotes: 'Bought from original owner in 2018. Used as a daily and a hunting rig. Recent: rear differential service, transfer case fluid, brake fluid flush, new tires (6,000 km). Selling because we just bought a Wrangler.',
    comparableSales: [
      { title: '2011 Jeep Liberty Sport — 168K km', date: '2026-04-04', location: 'Regina, SK', price: 11200, source: 'Manheim' },
      { title: '2012 Jeep Liberty Sport 4x4 — 142K km', date: '2026-03-19', location: 'Calgary, AB', price: 12500, source: 'Adesa' },
      { title: '2010 Jeep Liberty Sport — 198K km', date: '2026-02-26', location: 'Saskatoon, SK', price: 9400, source: 'BigIron' }
    ],
    publicQA: [
      { question: 'Does the sunroof leak?', askedBy: 'first_4x4', askedAt: '2 days ago', answer: 'Drains were cleared at last service. Tested with a hose — no leaks.', answeredBy: 'Seller', answeredAt: '2 days ago' }
    ],
    auctionTerms: [
      'Bidding closes at the time displayed; auto-extends 2 minutes for any bid in the final 2 minutes.',
      'Buyer pays applicable Saskatchewan provincial taxes.',
      'No buyer fee. Pickup in Saskatoon by appointment.',
      'Vehicle must be picked up or shipping arranged within 7 days of close.'
    ]
  },
  {
    id: '9',
    title: '2010 Mercedes-Benz B200',
    category: 'Hatchbacks',
    year: 2010,
    make: 'Mercedes-Benz',
    model: 'B200',
    location: 'Winnipeg, MB',
    currentBid: 5800,
    endTime: '2026-05-08T17:00:00Z',
    timeLeft: '2d 1h',
    auctionSource: 'GovDeals',
    imageUrl: PIC('fff83c5f-5b1e-4482-af3c-85a333a38f74.jpeg'),
    status: 'live',
    views: 220,
    fairValueRange: [6500, 8500],
    recommendedMaxBid: 7800,
    buyerEdgeScore: 'Risky Buy',
    confidenceScore: 52,
    isNative: false,
    sourceSlug: 'govdeals',
    sourceByline: 'Government and municipal surplus auctions',
    sourceDescription: 'GovDeals lists surplus assets from government and educational institutions. Listings often have limited photos and no inspections.',
    sourceUrl: 'https://www.govdeals.com/listing/example-9',
    currency: 'CAD',
    editorialBadge: 'Needs Caution',
    whyWatch: 'Looks priced right on paper, but only four exterior photos and no service records.',
    confidence: 2,
    editorialSections: ['needs_caution'],
    listingType: 'source_auction',
    cautionFlags: ['Buyer Caution', 'Low Info', 'Verify Terms'],
    whyWatching: 'The B200 is a Canadian-market hatchback with a small but loyal owner base. The price gap looks real, but the listing is light — four exterior photos, no engine bay shots, no service records. We feature it because the gap is meaningful, not because the data is strong.',
    whatToKnow: [
      'Current bid $5,800 CAD — under the $6.5–8.5K band',
      'Winnipeg, MB — government surplus pickup',
      'Limited photo set, no service history',
      'No inspection on file'
    ],
    knownIssues: 'Information is limited. Buyers should plan for an in-person inspection of the CVT, dual-clutch (where fitted), and front suspension before bidding past the recommended max.'
  },
  {
    id: '10',
    title: '2008 Jeep Compass Sport',
    category: 'SUVs',
    year: 2008,
    make: 'Jeep',
    model: 'Compass Sport',
    location: 'Regina, SK',
    currentBid: 4900,
    endTime: '2026-05-09T19:00:00Z',
    timeLeft: '3d 3h',
    auctionSource: 'Manheim',
    imageUrl: PIC('0bd9d20d-42b1-4a55-9f6b-df74bc5b7ddd.jpeg'),
    status: 'live',
    views: 410,
    fairValueRange: [5800, 7200],
    recommendedMaxBid: 6800,
    buyerEdgeScore: 'Risky Buy',
    confidenceScore: 48,
    isNative: false,
    sourceSlug: 'manheim',
    sourceByline: 'Wholesale auto auction',
    sourceDescription: 'Manheim runs dealer-only and commercial auctions across North America.',
    sourceUrl: 'https://www.manheim.com/listing/example-10',
    currency: 'CAD',
    editorialBadge: 'Low Info',
    whyWatch: 'Real price gap, but the listing has no service records and some visible body wear.',
    confidence: 2,
    editorialSections: ['needs_caution'],
    listingType: 'source_auction',
    cautionFlags: ['Buyer Caution', 'Low Info'],
    whyWatching: 'A bargain-band Compass with a meaningful gap to the comparable cohort. The catch: minimal photos, no service file, and visible body wear in the front-end shot. We surface it because the gap is real, not because the data inspires confidence.',
    whatToKnow: [
      'Current bid $4,900 CAD vs. fair-value band $5.8–7.2K',
      'Regina, SK — wholesale auction terms apply',
      'No service records on file',
      'Visible front-end and lower-body wear in photos'
    ],
    knownIssues: 'CVT history is the critical unknown on this generation. Verify transmission service records before bidding past the recommended max — replacement is the same price as the truck.'
  }
];

export const TREND_DATA = [
  { date: 'Oct', price: 340000 },
  { date: 'Nov', price: 355000 },
  { date: 'Dec', price: 348000 },
  { date: 'Jan', price: 370000 },
  { date: 'Feb', price: 385000 },
  { date: 'Mar', price: 392000 },
];
